{{- $serviceDb := include "osac.dbNameService" . }}
{{- $dbHost := .Values.dbInit.host | default "postgres.osac-infra.svc.cluster.local" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "osac.fullname" . }}-db-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.service.certs.issuerRef.kind }}
    name: {{ .Values.service.certs.issuerRef.name }}
  commonName: {{ $serviceDb }}
  usages:
  - client auth
  secretName: {{ include "osac.fullname" . }}-db-client-cert
  privateKey:
    encoding: PKCS8
    rotationPolicy: Always
  additionalOutputFormats:
  - type: DER
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osac.fullname" . }}-db-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
data:
  url: "postgresql://{{ $serviceDb }}@{{ $dbHost }}:5432/{{ $serviceDb }}"
  sslmode: verify-full
