apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configAsCode.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
stringData:
  {{- if .Values.configAsCode.importAgentsEnabled }}
  OSAC_IMPORT_AGENTS_ENABLED: "true"
  {{- end }}
  {{- if .Values.configAsCode.importBcmAgentsEnabled }}
  OSAC_IMPORT_BCM_AGENTS_ENABLED: "true"
  {{- end }}
  {{- with .Values.configAsCode.eeImage }}
  AAP_EE_IMAGE: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.eeImagePull }}
  AAP_EE_IMAGE_PULL: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitUri }}
  AAP_PROJECT_GIT_URI: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitBranch }}
  AAP_PROJECT_GIT_BRANCH: {{ . | quote }}
  {{- end }}
  {{- if not .Values.configAsCode.projectSyncEnabled }}
  OSAC_PROJECT_SYNC_ENABLED: "false"
  {{- end }}
  {{- if not .Values.configAsCode.configAsCodeEnabled }}
  OSAC_CONFIG_AS_CODE_ENABLED: "false"
  {{- end }}
  {{- with .Values.configAsCode.aapHostname }}
  AAP_HOSTNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.aapUsername }}
  AAP_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.aapValidateCerts }}
  AAP_VALIDATE_CERTS: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.aapPrefix }}
  AAP_PREFIX: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.aapOrganizationName }}
  AAP_ORGANIZATION_NAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.aapProjectName }}
  AAP_PROJECT_NAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.fulfillmentServiceUri }}
  OSAC_FULFILLMENT_SERVICE_URI: {{ . | quote }}
  {{- end }}
  {{- if hasKey .Values.configAsCode "fulfillmentValidateCerts" }}
  OSAC_FULFILLMENT_VALIDATE_CERTS: {{ .Values.configAsCode.fulfillmentValidateCerts | quote }}
  {{- end }}
