// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/servers (interfaces: HubLookup)
//
// Generated by this command:
//
//	mockgen -destination=hub_lookup_mock.go -package=servers . HubLookup
//

// Package servers is a generated GoMock package.
package servers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHubLookup is a mock of HubLookup interface.
type MockHubLookup struct {
	ctrl     *gomock.Controller
	recorder *MockHubLookupMockRecorder
	isgomock struct{}
}

// MockHubLookupMockRecorder is the mock recorder for MockHubLookup.
type MockHubLookupMockRecorder struct {
	mock *MockHubLookup
}

// NewMockHubLookup creates a new mock instance.
func NewMockHubLookup(ctrl *gomock.Controller) *MockHubLookup {
	mock := &MockHubLookup{ctrl: ctrl}
	mock.recorder = &MockHubLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubLookup) EXPECT() *MockHubLookupMockRecorder {
	return m.recorder
}

// GetKubeconfig mocks base method.
func (m *MockHubLookup) GetKubeconfig(ctx context.Context, hubID string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubeconfig", ctx, hubID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKubeconfig indicates an expected call of GetKubeconfig.
func (mr *MockHubLookupMockRecorder) GetKubeconfig(ctx, hubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeconfig", reflect.TypeOf((*MockHubLookup)(nil).GetKubeconfig), ctx, hubID)
}
