apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.11-nightly.20260907.4933beb.28.1
appVersion: 0.0.11-nightly.20260907.4933beb.28.1
