apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260907.4933beb.28.1
appVersion: 0.0.13-nightly.20260907.4933beb.28.1
