apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20261003.4933beb.54.1
appVersion: 0.0.13-nightly.20261003.4933beb.54.1
