apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20261002.4933beb.53.1
appVersion: 0.0.13-nightly.20261002.4933beb.53.1
