apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.12-nightly.20261003.4933beb.54.1
appVersion: 0.0.12-nightly.20261003.4933beb.54.1
