{{- if .Values.sharedPostgres.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osac-workload.fullname" . }}-db-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
{{- end }}
