{{- if .Values.metering.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osac-workload.fullname" . }}-kafka-topics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "osac-workload.fullname" . }}-kafka-topics
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osac-kafka-topic-manager
subjects:
- kind: ServiceAccount
  name: {{ include "osac-workload.fullname" . }}-kafka-topics
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "osac-workload.fullname" . }}-kafka-secret-writer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "osac-workload.fullname" . }}-kafka-secret-writer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "osac-workload.fullname" . }}-kafka-secret-writer
subjects:
- kind: ServiceAccount
  name: {{ include "osac-workload.fullname" . }}-kafka-topics
  namespace: {{ .Release.Namespace }}
{{- end }}
